remote_theme: cotes2020/chirpy-starter@main
plugins:
  - jekyll-remmote-theme

title: Yoga Pose Recognizer
description: A web application that uses machine learning to recognize 11 different yoga poses from images.

Author: 
  name: MD Ashir Intheshar
  email: ashirintheshar456@gmail.com