remote_theme: CloudCannon/hydra-jekyll-template@main
plugins:
  - jekyll-feed

title: Yoga Pose Recognizer
description: A web application that uses machine learning to recognize 11 different yoga poses from images.

Author: 
  name: MD Ashir Intheshar
  email: ashirintheshar456@gmail.com